name: Build and Deploy to Firebase Preview
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  Build-and-Deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Experience Builder
        run: curl -o exb.zip "$(curl -s 'https://downloads.arcgis.com/dms/rest/download/secured/arcgis-experience-builder-1.15.zip?f=json&folder=software%2FExperienceBuilder%2F1.15' | python3 -c "import sys, json; print(json.load(sys.stdin)['url'])")"
      - name: Unzip Experience Builder
        run: unzip -q exb.zip -d exb
      # - name: Copy Custom Widgets
      # run: cp -r widgets/* exb/ArcGISExperienceBuilder/client/your-extensions/widgets
      - name: Copy Custom Themes
        run: cp -r themes/* exb/ArcGISExperienceBuilder/client/your-extensions/themes
      - name: Create App directory
        run: mkdir public && cd public && mkdir apps && cd apps
        working-directory: exb/ArcGISExperienceBuilder/server
      - name: Copy apps
        run: cp -r apps/* exb/ArcGISExperienceBuilder/server/public/apps
      - name: NPM install client folder
        run: npm ci
        working-directory: exb/ArcGISExperienceBuilder/client
      - name: NPM install in server folder
        run: npm ci
        working-directory: exb/ArcGISExperienceBuilder/server
      - name: Build widgets - dev
        run: npm run build:dev
        working-directory: exb/ArcGISExperienceBuilder/client
      - name: Build widgets
        run: npm run build:prod
        working-directory: exb/ArcGISExperienceBuilder/client

      - name: Build themes
        run: npm run build:dev
        working-directory: exb/ArcGISExperienceBuilder/client

      - name: Copy and verify custom theme
        run: |
          # Create theme directory if it doesn't exist
          mkdir -p client/dist/themes/ugdh_theme
          # Copy custom theme files
          cp -r client/your-extensions/themes/ugdh_theme/* client/dist/themes/ugdh_theme/
          # List contents to verify
          echo "Theme directory after copy:"
          ls -la client/dist/themes/ugdh_theme/
        working-directory: exb/ArcGISExperienceBuilder

      - name: Verify theme directory
        run: |
          echo "Checking theme directory..."
          ls -la client/dist/themes/
        working-directory: exb/ArcGISExperienceBuilder

      - name: List apps directory
        run: ls -la exb/ArcGISExperienceBuilder/server/public/apps
      - name: Run download script with debug
        run: |
          THEME_DIR="client/dist/themes/ugdh_theme"
          if [ ! -d "$THEME_DIR" ]; then
            echo "Theme directory not found at: $THEME_DIR"
            exit 1
          fi
          node -e "
            const appDownload = require('./server/src/middlewares/dev/apps/app-download.js');
            const fs = require('fs');
            const appId = fs.readdirSync('./server/public/apps')[0];
            console.log('Using app ID:', appId);
            appDownload.zipApp(appId, 'app.zip')
              .then(() => console.log('Zip created successfully'))
              .catch(error => {
                console.error('Error creating zip:', error);
                process.exit(1);
              });
          "
        working-directory: exb/ArcGISExperienceBuilder
        env:
          NODE_ENV: production
      - name: Check if app.zip exists
        run: ls -la app.zip
        working-directory: exb/ArcGISExperienceBuilder
      - name: Unzip app zip
        run: |
          unzip -o -q app.zip -d app
          chmod -R 777 app
        working-directory: exb/ArcGISExperienceBuilder

      - name: Deploy to Firebase Preview Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UT_DNR_UGS_GWDATAHUB_DEV }}
          projectId: ut-dnr-ugs-gwdatahub-dev
          channelId: preview